services:
  devenv:
    build: .
    image: devenv:local
    container_name: devenv
    volumes:
      - ./:/work
    working_dir: /work
    command: sleep infinity
    tty: true
    stdin_open: true
    ports:
      - "1111:1111"
