name = "axum-on-workers"
main = "build/index.js"

[build]
command = "cargo install \"worker-build@^0.8\" && worker-build --release"

[dev]
ip = "0.0.0.0"
port = 1111
local_protocol = "http"

[assets]
directory = "./public"
binding = "ASSETS"