# The URL the site will be built for
base_url = "https://axum-on-workers.redham28.workers.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
smart_punctuation = true
definition_list = true
bottom_footnotes = true

[extra]
# Put all your custom variables here
